### ISSUE TITLE
DAOS container to container object copy using mpifileutils

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-experiments#27]
- [x] Setup DAOS in single node VM
- [x] Create pool and source and destination containers
- [x] Create objects in source container
- [x] Copy objects from source container to destination containers using mpifiltuils (with daos support)
- [x] Verify Target container for copied objects
- [x] Document the process in quickstart

**Comment by rajkumarpatel2602** [comment]
Done : Created a POSIX object in source container and  copied to destination container using mpifileutils. 

ToDo - Documentation.

**Comment by rajkumarpatel2602** [comment]
FYI, for mpifileutils setup and object copy operation, I have taken following divergences.

- build_deps.sh file is referenced not from https://mpifileutils.readthedocs.io/en/v0.10.1/build.html#build-everything-directly , but I had referred that from https://github.com/hpc/mpifileutils/blob/master/doc/rst/build.rst
- I have to reduce number of process parameter to 1. instead of going with _-np 3_
