### ISSUE TITLE
Poor/0/ indendation, No return from main, memory leaks, no mention of how to compile, no make/cmakeList

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-experiments#54]
https://github.com/Seagate/cortx-experiments/blob/6bd545ba15b076f742fcc915c28557970241a290/B%20epsilon%20tree%20Research%20and%20Implementation/src/Source.cpp#L231

Is the normal/acceptable of programming by  Seagate Employees? 

I know this is a POC code, but at the same time it's on github. 

Please make github a better place when you add your code, if that's not possible, refrain from making it a more poor. 

Make sure your code quality does not bring down the average code quality of cpp files on github.

**Comment by novium258** [comment]
Hi @raikrahul ! Thanks you so much for participating in our community. If you read our contributing guidelines, we aim to create a respectful and inclusive community for everyone. Part of this is ensuring that criticism is always constructive, helpful, and doesn't shame or attack others. Since this is an open source project, it is always in development and there is always room for improvement. We welcome suggested changes, but please keep the contributing guidelines in mind moving forward. Thank you!
