### ISSUE TITLE
Make this file readable and renderable. Correct the english as well. 

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-experiments#55]
https://github.com/Seagate/cortx-experiments/blob/6bd545ba15b076f742fcc915c28557970241a290/B%20epsilon%20tree%20Research%20and%20Implementation/objective/objective.txt#L1

**Comment by raikrahul** [comment]
B epsilon tree Research and Implementation

/docs/B epsilon tree.docx

This has spaces trimmed and over expanded, also the English is wrong.


Please make sure to not bring the average quality of .docx files down on the github when you upload a file on github.

**Comment by novium258** [comment]
Hi @raikrahul ! Thanks you so much for participating in our community. If you read our contributing guidelines, we aim to create a respectful and inclusive community for everyone. Part of this is ensuring that criticism is always constructive, helpful, and doesn't shame or attack others. Since this is an open source project, it is always in development and there is always room for improvement. We welcome suggested changes, but please keep the contributing guidelines in mind moving forward. Thank you!
